"""Check that the released TPx companion still supports every number in the paper.

Run from the repository root::

    python3 validate_public_companion.py

Sections:

1. corpus structure (rows, unique identifiers, allowed labels, scope
   decisions, bibliography, frozen sheet, descriptive table);
2. published counts, regenerated by ``corpus/regenerate_paper_counts.py``
   and compared with the values stated in the publication;
3. coverage updates (June 5 candidate log and search log, June 8 follow-up);
4. reliability audit (sample, agreement, kappa, Jaccard, reconciliation);
5. reporting cards, validated against the JSON Schema by
   ``reporting_card/validate_cards.py`` (needs PyYAML and jsonschema from
   ``requirements.txt``).

``corpus/CONSISTENCY_CHECK.md`` lists the same checks in prose; keep both in
sync when either changes.
"""
from __future__ import annotations

import csv
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CORPUS = ROOT / "corpus"
AUDIT_DIR = CORPUS / "second_annotator"

ALLOWED = {
    "scope_label": {"Core", "Adjacent", "Component", "Background"},
    "transfer_point": {"Retrieval", "Generation", "Evaluation"},
    "translation_strategy": {
        "Translate-then-retrieve",
        "Retrieve-then-translate",
        "Language-agnostic",
        "Hybrid",
        "N/A",
    },
    "resource_level": {"High", "Low", "Mixed", "N/A"},
    "domain": {
        "Open",
        "General",
        "Medical",
        "Legal",
        "Cultural",
        "News",
        "Agriculture",
        "Enterprise",
        "Climate",
        "Religious",
        "Education",
    },
}
ALLOWED_CONFIDENCE = {"high", "medium"}
CODING_FIELDS = (
    "scope_label",
    "transfer_point",
    "translation_strategy",
    "resource_level",
)
DESCRIPTIVE_TABLE_FIELDS = (
    "id",
    "title",
    "authors",
    "year",
    "venue",
    "url",
    "transfer_point",
    "translation_strategy",
    "resource_level",
    "domain",
    "citation_key",
    "scope_confidence",
    "scope_rationale",
    "notes",
)

# Numbers stated in the publication. Section 2 compares them with the counts
# regenerated from the data files by corpus/regenerate_paper_counts.py.
EXPECTED_COUNTS = {
    "evidence_base": 116,
    "scope": {"Core": 42, "Adjacent": 13, "Component": 50, "Background": 11},
    "core": {
        "n": 42,
        "stages": {"Retrieval": 38, "Generation": 42, "Evaluation": 15},
        "stage_combinations": {"R+G": 26, "R+G+E": 12, "G+E": 3, "G": 1},
        "strategy": {
            "Language-agnostic": 23,
            "Hybrid": 10,
            "Translate-then-retrieve": 1,
            "Retrieve-then-translate": 0,
            "N/A": 8,
        },
        "resource": {"Mixed": 33, "High": 5, "Low": 4, "N/A": 0},
        "domain_open": 32,
        "domain_specialized_total": 10,
    },
    "sensitivity": {
        "medium_confidence_core_count": 3,
        "n": 39,
        "stages": {"Retrieval": 35, "Generation": 39, "Evaluation": 13},
    },
    "coverage_update_june5": {"candidates": 37, "integrated": 27, "excluded": 10},
    "targeted_followup_june8": {"assessed": 8, "integrated": 7, "unresolved": 1},
    "reliability_audit": {
        "disagreements": 18,
        "resolved_to_initial": 11,
        "resolved_to_audit": 7,
        "fields": {
            "scope_label": {"disagreements": 3, "resolved_to_initial": 3, "resolved_to_audit": 0},
            "transfer_point": {"disagreements": 7, "resolved_to_initial": 3, "resolved_to_audit": 4},
            "translation_strategy": {"disagreements": 5, "resolved_to_initial": 3, "resolved_to_audit": 2},
            "resource_level": {"disagreements": 3, "resolved_to_initial": 2, "resolved_to_audit": 1},
        },
    },
}
# field: (exact matches out of 20, agreement rate, Cohen's kappa)
EXPECTED_AGREEMENT = {
    "scope_label": ("17", "0.8500", "0.7581"),
    "transfer_point": ("13", "0.6500", "0.5053"),
    "translation_strategy": ("15", "0.7500", "0.5816"),
    "resource_level": ("17", "0.8500", "0.7143"),
}
EXPECTED_STAGE_KAPPA = {"Retrieval": "0.5000", "Generation": "1.0000", "Evaluation": "0.5294"}
EXPECTED_MEAN_JACCARD = "0.8667"
EXPECTED_AUDIT_STRATA = {"Core": 11, "Adjacent": 3, "Component": 5, "Background": 1}
EXPECTED_RECONCILIATION = {"keep_current": 11, "accept_audit": 7}
EXPECTED_JUNE5_PAPER_IDS = {f"P{number:03d}" for number in range(83, 110)}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def stage_set(value: str) -> frozenset[str]:
    return frozenset(part.strip() for part in value.split("|") if part.strip())


def normalize_title(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def check(condition: bool, message: str, errors: list[str]) -> None:
    if not condition:
        errors.append(message)


def compare_expected(expected, actual, path: str, errors: list[str]) -> None:
    """Recursively require every published value to equal the regenerated one."""
    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            errors.append(f"{path}: regenerated counts do not contain a mapping")
            return
        for key, value in expected.items():
            if key not in actual:
                errors.append(f"{path}.{key}: missing from regenerated counts")
                continue
            compare_expected(value, actual[key], f"{path}.{key}", errors)
    elif expected != actual:
        errors.append(f"{path}: regenerated {actual!r}, publication states {expected!r}")


# 1. Corpus structure -------------------------------------------------------


def validate_corpus(errors: list[str]) -> None:
    papers = read_csv(CORPUS / "papers.csv")
    check(len(papers) == 116, f"papers.csv has {len(papers)} rows, expected 116", errors)

    ids = [row["id"] for row in papers]
    check(len(set(ids)) == len(ids), "papers.csv contains duplicate paper IDs", errors)
    keys = [row["citation_key"] for row in papers]
    check(len(set(keys)) == len(keys), "papers.csv contains duplicate citation keys", errors)

    for row in papers:
        for field in ("scope_label", "translation_strategy", "resource_level", "domain"):
            check(
                row[field] in ALLOWED[field],
                f"{row['id']}: {field}={row[field]!r} is not an allowed label",
                errors,
            )
        stages = stage_set(row["transfer_point"])
        check(
            bool(stages) and stages <= ALLOWED["transfer_point"],
            f"{row['id']}: transfer_point={row['transfer_point']!r} is not an allowed stage set",
            errors,
        )

    decisions = read_csv(CORPUS / "scope_decisions.csv")
    decision_by_id = {row["paper_id"]: row for row in decisions}
    check(
        len(decisions) == len(papers) and set(decision_by_id) == set(ids),
        "scope_decisions.csv does not cover exactly the corpus IDs",
        errors,
    )
    for row in papers:
        decision = decision_by_id.get(row["id"])
        if decision is None:
            continue
        check(
            decision["new_scope"] == row["scope_label"],
            f"{row['id']}: scope in scope_decisions.csv differs from papers.csv",
            errors,
        )
        check(
            decision["confidence"] in ALLOWED_CONFIDENCE,
            f"{row['id']}: confidence={decision['confidence']!r} is not high or medium",
            errors,
        )

    bib_text = (CORPUS / "papers.bib").read_text(encoding="utf-8")
    bib_keys = re.findall(r"@\w+\s*\{\s*([^,\s]+)", bib_text)
    check(len(bib_keys) == 116, f"papers.bib has {len(bib_keys)} entries, expected 116", errors)
    check(
        set(bib_keys) == set(keys),
        "papers.bib keys do not match the corpus citation keys exactly",
        errors,
    )

    frozen = CORPUS / "papers_frozen_camera_ready.csv"
    check(
        frozen.exists() and frozen.read_bytes() == (CORPUS / "papers.csv").read_bytes(),
        "papers_frozen_camera_ready.csv is not byte-identical to papers.csv "
        "(record the change in the README changelog and update the published counts)",
        errors,
    )

    table = read_csv(CORPUS / "core_papers_descriptive_table.csv")
    core = [row for row in papers if row["scope_label"] == "Core"]
    check(
        len(table) == len(core),
        f"core_papers_descriptive_table.csv has {len(table)} rows, expected {len(core)}",
        errors,
    )
    for table_row, paper in zip(table, core):
        decision = decision_by_id.get(paper["id"], {})
        expected = {}
        for field in DESCRIPTIVE_TABLE_FIELDS:
            if field == "scope_confidence":
                expected[field] = decision.get("confidence", "")
            elif field == "scope_rationale":
                expected[field] = decision.get("decision_basis", "")
            else:
                expected[field] = paper.get(field, "")
        check(
            table_row == expected,
            f"core_papers_descriptive_table.csv row {table_row.get('id')} is out of date; "
            "rerun corpus/generate_core_descriptive_table.py",
            errors,
        )


# 2. Published counts -------------------------------------------------------


def validate_paper_counts(errors: list[str]) -> None:
    result = subprocess.run(
        [sys.executable, str(CORPUS / "regenerate_paper_counts.py"), "--json"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        errors.append(
            "regenerate_paper_counts.py failed: "
            + (result.stderr.strip() or result.stdout.strip())
        )
        return
    compare_expected(EXPECTED_COUNTS, json.loads(result.stdout), "counts", errors)


# 3. Coverage updates -------------------------------------------------------


def validate_collection_updates(errors: list[str]) -> None:
    papers = {row["id"]: row for row in read_csv(CORPUS / "papers.csv")}

    candidates = read_csv(CORPUS / "coverage_check_candidates.csv")
    integrated_ids = []
    for row in candidates:
        check(
            row["decision_rationale"].strip() != "",
            f"{row['candidate_id']}: missing decision rationale",
            errors,
        )
        if row["decision"].startswith("new_"):
            paper = papers.get(row["paper_id"])
            if paper is None:
                errors.append(
                    f"{row['candidate_id']}: paper_id {row['paper_id']!r} is not in papers.csv"
                )
                continue
            integrated_ids.append(row["paper_id"])
            check(
                normalize_title(paper["title"]) == normalize_title(row["title"]),
                f"{row['candidate_id']}: title differs from {row['paper_id']}",
                errors,
            )
            check(
                row["decision"] == "new_" + paper["scope_label"].lower(),
                f"{row['candidate_id']}: decision {row['decision']} does not match the "
                f"{paper['scope_label']} scope of {row['paper_id']}",
                errors,
            )
        else:
            check(
                row["decision"] == "exclude" and row["paper_id"] == "",
                f"{row['candidate_id']}: decision {row['decision']!r} must be exclude "
                "with an empty paper_id",
                errors,
            )
    check(
        len(integrated_ids) == 27 and set(integrated_ids) == EXPECTED_JUNE5_PAPER_IDS,
        "June 5 integrated candidates do not map one-to-one onto P083-P109",
        errors,
    )

    followup = read_csv(CORPUS / "targeted_followup.csv")
    for row in followup:
        check(
            row["title"].strip() != "" and row["url"].strip() != "",
            f"{row['candidate_id']}: missing title or url",
            errors,
        )
        if row["decision"] == "Core":
            paper = papers.get(row["paper_id"])
            if paper is None:
                errors.append(
                    f"{row['candidate_id']}: paper_id {row['paper_id']!r} is not in papers.csv"
                )
                continue
            check(
                paper["citation_key"] == row["citation_key"]
                and paper["title"] == row["title"]
                and paper["url"] == row["url"],
                f"{row['candidate_id']}: citation_key, title, or url differs from {row['paper_id']}",
                errors,
            )
        else:
            check(
                row["decision"] == "not_integrated"
                and row["paper_id"] == ""
                and row["decision_basis"].strip() != "",
                f"{row['candidate_id']}: an unresolved row must have decision not_integrated, "
                "no paper_id, and a recorded reason",
                errors,
            )

    log = read_csv(CORPUS / "coverage_check_search_log.csv")
    check(len(log) == 17, f"coverage_check_search_log.csv has {len(log)} passes, expected 17", errors)
    for row in log:
        linked = [
            candidate
            for candidate in candidates
            if row["search_id"] in candidate["discovery_search_ids"].split("|")
        ]
        linked_core = [candidate for candidate in linked if candidate["decision"] == "new_core"]
        check(
            row["linked_candidate_rows"] == str(len(linked))
            and row["linked_core_decisions"] == str(len(linked_core)),
            f"search log {row['search_id']}: linked columns do not reproduce from the candidate file",
            errors,
        )


# 4. Reliability audit ------------------------------------------------------


def validate_reliability_audit(errors: list[str]) -> None:
    papers = {row["id"]: row for row in read_csv(CORPUS / "papers.csv")}

    blind = read_csv(AUDIT_DIR / "second_annotator_blind_sheet.csv")
    returned = read_csv(AUDIT_DIR / "second_annotator_blind_sheet_remplis.csv")
    frozen = read_csv(AUDIT_DIR / "primary_coding_pre_reconciliation.csv")
    blind_ids = [row["paper_id"] for row in blind]
    check(
        len(blind_ids) == 20
        and blind_ids == [row["paper_id"] for row in returned]
        and blind_ids == [row["id"] for row in frozen],
        "blind sheet, returned sheet, and frozen primary sheet do not list the same 20 papers",
        errors,
    )
    check(
        all(not row[key].strip() for row in blind for key in row if key.startswith("audit_")),
        "the blind sheet sent to the annotator is not empty",
        errors,
    )
    check(
        all(row[f"audit_{field}"].strip() for row in returned for field in CODING_FIELDS),
        "the returned sheet has empty labels",
        errors,
    )
    check(
        Counter(row["scope_label"] for row in frozen) == EXPECTED_AUDIT_STRATA,
        "audit sample strata differ from 11 Core / 3 Adjacent / 5 Component / 1 Background",
        errors,
    )

    summary = read_csv(AUDIT_DIR / "audit_scoring_results_pre_reconciliation.csv")
    observed = {
        row["field"]: (row["exact_matches"], row["agreement_rate"], row["cohen_kappa"])
        for row in summary
    }
    check(
        observed == EXPECTED_AGREEMENT,
        "pre-reconciliation exact agreement or kappa values differ from the publication",
        errors,
    )
    stage_rows = read_csv(AUDIT_DIR / "audit_transfer_stage_results_pre_reconciliation.csv")
    check(
        {row["stage"]: row["cohen_kappa"] for row in stage_rows} == EXPECTED_STAGE_KAPPA,
        "stage-wise transfer-point kappa values differ from the publication",
        errors,
    )
    jaccard = read_csv(AUDIT_DIR / "audit_jaccard_pre_reconciliation.csv")
    per_paper = [row for row in jaccard if row["paper_id"] != "MEAN"]
    mean_rows = [row for row in jaccard if row["paper_id"] == "MEAN"]
    check(
        len(per_paper) == 20
        and len(mean_rows) == 1
        and mean_rows[0]["jaccard"] == EXPECTED_MEAN_JACCARD,
        "mean transfer-point Jaccard differs from the published 0.8667",
        errors,
    )

    pre = read_csv(AUDIT_DIR / "audit_disagreements_pre_reconciliation.csv")
    reconciliation = read_csv(AUDIT_DIR / "audit_disagreements_for_reconciliation.csv")
    check(len(pre) == 18, f"expected 18 pre-reconciliation disagreements, found {len(pre)}", errors)
    check(
        {(row["paper_id"], row["field"]) for row in pre}
        == {(row["paper_id"], row["field"]) for row in reconciliation},
        "reconciliation log does not cover exactly the pre-reconciliation disagreements",
        errors,
    )
    check(
        Counter(row["adjudication_decision"] for row in reconciliation) == EXPECTED_RECONCILIATION,
        "reconciliation decision counts differ from 11 keep_current / 7 accept_audit",
        errors,
    )
    check(
        all(row["adjudication_note"].strip() for row in reconciliation),
        "reconciliation rows without an evidence-based note",
        errors,
    )

    accepted = set()
    for row in reconciliation:
        if row["adjudication_decision"] == "accept_audit":
            accepted.add((row["paper_id"], row["field"]))
            expected = row["audit_label"]
        else:
            expected = row["current_label"]
        actual = papers[row["paper_id"]][row["field"]]
        if row["field"] == "transfer_point":
            expected, actual = stage_set(expected), stage_set(actual)
        check(
            expected == actual,
            f"{row['paper_id']} {row['field']}: papers.csv does not reflect the reconciliation decision",
            errors,
        )
    differences = set()
    for row in frozen:
        for field in CODING_FIELDS:
            before, after = row[field], papers[row["id"]][field]
            if field == "transfer_point":
                before, after = stage_set(before), stage_set(after)
            if before != after:
                differences.add((row["id"], field))
    check(
        differences == accepted,
        "the frozen 20-paper sheet and papers.csv differ in cells other than the seven accepted audit labels",
        errors,
    )


# 5. Reporting cards --------------------------------------------------------


def validate_reporting_cards(errors: list[str]) -> None:
    cards = sorted((ROOT / "reporting_card" / "examples").glob("*.yaml"))
    check(len(cards) == 5, f"expected 5 reporting-card examples, found {len(cards)}", errors)
    result = subprocess.run(
        [sys.executable, "validate_cards.py", *map(str, cards)],
        cwd=ROOT / "reporting_card",
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        errors.append(
            "reporting-card validation failed: "
            + (result.stderr.strip() + "\n" + result.stdout.strip()).strip()
        )


def main() -> int:
    errors: list[str] = []
    validate_corpus(errors)
    validate_paper_counts(errors)
    validate_collection_updates(errors)
    validate_reliability_audit(errors)
    validate_reporting_cards(errors)

    if errors:
        print("Public companion validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("Public companion validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
